import { Category, Question } from "./types";

export const QUESTIONS: Question[] = [
  // 1-6: Oscillations
  { id: 1, category: Category.OSCILLATIONS, text: "Дифференциальное уравнение гармонических колебаний. Покажите, что в колебательном контуре, состоящем из конденсатора и катушки индуктивности, не обладающей сопротивлением, возникают свободные незатухающие гармонические колебания." },
  { id: 2, category: Category.OSCILLATIONS, text: "Покажите, что полная энергия колебательного контура, не обладающего сопротивлением, при гармонических колебаниях остается неизменной." },
  { id: 3, category: Category.OSCILLATIONS, text: "Векторное представление колебаний. Сложение колебаний одинаковой частоты и направления. (Примеры задач на сложение косинусов)." },
  { id: 4, category: Category.OSCILLATIONS, text: "Свободные затухающие электромагнитные колебания. Задача: Колебательный контур (L=6 мкГн, C=10 нФ, R=10 Ом). Определите отношение энергии магнитного поля к энергии электрического поля при максимальном токе." },
  { id: 5, category: Category.OSCILLATIONS, text: "Вынужденные электромагнитные колебания. Уравнение и его решение. Использование векторных диаграмм." },
  { id: 6, category: Category.OSCILLATIONS, text: "Как рассчитать мощность в цепи переменного тока? Выведите формулу мгновенной и средней мощности." },

  // 7-17: Waves & Optics
  { id: 7, category: Category.WAVES_OPTICS, text: "Характеристики волн. Уравнение плоской волны." },
  { id: 8, category: Category.WAVES_OPTICS, text: "Электромагнитные волны и их свойства." },
  { id: 9, category: Category.WAVES_OPTICS, text: "Энергия электромагнитной волны. Вектор Умова-Пойнтинга." },
  { id: 10, category: Category.WAVES_OPTICS, text: "При каких условиях можно наблюдать интерференцию света? Какие волны называются когерентными? Как получить когерентные источники света?" },
  { id: 11, category: Category.WAVES_OPTICS, text: "Задача: При изменении длины волны света в опыте Юнга расстояние между максимумами увеличилось в 2 раза. Как изменилась длина волны?" },
  { id: 12, category: Category.WAVES_OPTICS, text: "Условия максимума и минимума при интерференции." },
  { id: 13, category: Category.WAVES_OPTICS, text: "Чем естественный свет отличается от линейно поляризованного? При помощи какого прибора можно определить, поляризован ли свет?" },
  { id: 14, category: Category.WAVES_OPTICS, text: "Задача: Чему равен угол между поляризатором и анализатором, если интенсивность уменьшается в 4 раза?" },
  { id: 15, category: Category.WAVES_OPTICS, text: "Задача: Определите угол Брюстера при отражении света от воды (n=1.33)." },
  { id: 16, category: Category.WAVES_OPTICS, text: "Сформулируйте принцип Гюйгенса-Френеля. Что такое зоны Френеля?" },
  { id: 17, category: Category.WAVES_OPTICS, text: "Задача: Круглое отверстие открывает три зоны Френеля. Как изменится интенсивность в центре, если открыть четыре зоны?" },

  // 18-36: Quantum Physics
  { id: 18, category: Category.QUANTUM, text: "Какие законы сохранения выполняются при эффекте Комптона? В чем состоит этот эффект?" },
  { id: 19, category: Category.QUANTUM, text: "Что такое фотоэффект? Какой закон сохранения выражает уравнение Эйнштейна? Запишите это уравнение." },
  { id: 20, category: Category.QUANTUM, text: "Задача: Красная граница фотоэффекта 500 нм. Найти работу выхода и макс. скорость электронов при λ=400 нм." },
  { id: 21, category: Category.QUANTUM, text: "Что отличает тепловое излучение от других видов? Сформулируйте законы теплового излучения." },
  { id: 22, category: Category.QUANTUM, text: "Задача: Энергия черного тела за 1с равна 10 кВт, максимум излучения на 0.8 мкм. Найти площадь тела." },
  { id: 23, category: Category.QUANTUM, text: "Задача: Максимум излучения сместился с 2.1 мкм до 0.7 мкм. Во сколько раз изменилась энергетическая светимость?" },
  { id: 24, category: Category.QUANTUM, text: "Задача: Работа выхода 3.7 эВ. Какую энергию должны иметь фотоны, чтобы кинетическая энергия электронов была 2 эВ?" },
  { id: 25, category: Category.QUANTUM, text: "Объясните суть эффекта Комптона. Какими законами сохранения объясняется этот эффект?" },
  { id: 26, category: Category.QUANTUM, text: "Задача: Комптоновское рассеяние на 90 градусов, энергия распределилась поровну. Найти энергию падающего фотона." },
  { id: 27, category: Category.QUANTUM, text: "Постулаты Бора. Боровская модель атома водорода." },
  { id: 28, category: Category.QUANTUM, text: "Определить радиус третьей боровской орбиты атома водорода." },
  { id: 29, category: Category.QUANTUM, text: "Определить потенциальную, кинетическую и полную энергию электрона на второй боровской орбите." },
  { id: 30, category: Category.QUANTUM, text: "Определить скорость электрона на первой боровской орбите атома водорода." },
  { id: 31, category: Category.QUANTUM, text: "Волны де Бройля. Определите длину волны для электрона со скоростью 10^5 м/с." },
  { id: 32, category: Category.QUANTUM, text: "Соотношения неопределенностей Гейзенберга." },
  { id: 33, category: Category.QUANTUM, text: "Волновая функция и ее статистический смысл." },
  { id: 34, category: Category.QUANTUM, text: "Уравнение Шредингера." },
  { id: 35, category: Category.QUANTUM, text: "Частица в одномерной прямоугольной потенциальной яме с бесконечно высокими стенками." },
  { id: 36, category: Category.QUANTUM, text: "Атом водорода в квантовой механике. Уравнение Шредингера. Квантовые числа." },

  // 37-47: Solid State / Semiconductors (Categorized as Quantum/Solid State, putting in Quantum/Materials mix)
  { id: 37, category: Category.QUANTUM, text: "Спин. Спиновое квантовое число. Принцип запрета Паули." },
  { id: 38, category: Category.QUANTUM, text: "Зонная структура металлов, диэлектриков и полупроводников." },
  { id: 39, category: Category.QUANTUM, text: "Проводники. Функция распределения электронов по энергиям. Вырожденный электронный газ." },
  { id: 40, category: Category.QUANTUM, text: "Контакт двух проводников. Контактная разность потенциалов." },
  { id: 41, category: Category.QUANTUM, text: "Собственная проводимость полупроводников." },
  { id: 42, category: Category.QUANTUM, text: "Донорная проводимость полупроводников." },
  { id: 43, category: Category.QUANTUM, text: "Акцепторная проводимость полупроводников." },
  { id: 44, category: Category.QUANTUM, text: "p-n-переход." },
  { id: 45, category: Category.QUANTUM, text: "Явление Зеебека. ТермоЭДС." },
  { id: 46, category: Category.QUANTUM, text: "Явление Пельтье." },
  { id: 47, category: Category.QUANTUM, text: "Выпрямление на контакте металл-полупроводник." },

  // 48-62: Thermodynamics
  { id: 48, category: Category.THERMODYNAMICS, text: "Идеальный газ. Уравнение состояния идеального газа." },
  { id: 49, category: Category.THERMODYNAMICS, text: "Основное уравнение молекулярно-кинетической теории газов." },
  { id: 50, category: Category.THERMODYNAMICS, text: "Средняя длина свободного пробега молекул." },
  { id: 51, category: Category.NUCLEAR, text: "Состав атомного ядра. Массовое и зарядовое числа." }, // Moved to Nuclear based on context, though list order is mixed
  { id: 52, category: Category.THERMODYNAMICS, text: "Внутренняя энергия." },
  { id: 53, category: Category.THERMODYNAMICS, text: "Работа, совершаемая газом при расширении." },
  { id: 54, category: Category.THERMODYNAMICS, text: "Первое начало термодинамики." },
  { id: 55, category: Category.THERMODYNAMICS, text: "Теплоемкость идеального газа в различных процессах." },
  { id: 56, category: Category.THERMODYNAMICS, text: "Энтропия. Изменение энтропии идеального газа." },
  { id: 57, category: Category.THERMODYNAMICS, text: "Неравновесные процессы. Второе начало термодинамики." },
  { id: 58, category: Category.THERMODYNAMICS, text: "Изменение энтропии в неравновесных процессах." },
  { id: 59, category: Category.THERMODYNAMICS, text: "Энтропия и вероятность." },
  { id: 60, category: Category.THERMODYNAMICS, text: "Круговые процессы (циклы). КПД цикла. Тепловые машины." },
  { id: 61, category: Category.THERMODYNAMICS, text: "Цикл Карно. КПД цикла Карно." },
  { id: 62, category: Category.THERMODYNAMICS, text: "Явления переноса." },

  // 63-81: Nuclear Physics
  { id: 63, category: Category.NUCLEAR, text: "Дефект масс и энергия связи атомных ядер." },
  { id: 64, category: Category.NUCLEAR, text: "Радиоактивное излучение и его виды." },
  { id: 65, category: Category.NUCLEAR, text: "Закон радиоактивного распада." },
  { id: 66, category: Category.NUCLEAR, text: "Альфа-распад." },
  { id: 67, category: Category.NUCLEAR, text: "Бета-распад. Нейтрино." },
  { id: 68, category: Category.NUCLEAR, text: "Ядерные реакции и их основные типы." },
  { id: 69, category: Category.NUCLEAR, text: "Спонтанное деление тяжелых ядер. Цепная реакция." },
  { id: 70, category: Category.NUCLEAR, text: "Понятие о ядерной энергетике." },
  { id: 71, category: Category.NUCLEAR, text: "Термоядерный синтез." },
  { id: 72, category: Category.NUCLEAR, text: "Задача: Из азота-14 + альфа-частица -> кислород-17. Запишите реакцию." },
  { id: 73, category: Category.NUCLEAR, text: "Укажите состав ядра изотопа свинца-208." },
  { id: 74, category: Category.NUCLEAR, text: "Как изменится массовое число и заряд при альфа-распаде?" },
  { id: 75, category: Category.NUCLEAR, text: "Какое ядро, поглотив нейтрон, а затем испустив протон, дает кислород-17?" },
  { id: 76, category: Category.NUCLEAR, text: "Задача: Какая часть радиоактивного вещества останется спустя 2 периода полураспада?" },
  { id: 77, category: Category.NUCLEAR, text: "Задача: Сравнение ускорения альфа-частицы и бета-частицы в электрическом поле." },
  { id: 78, category: Category.NUCLEAR, text: "На сколько единиц отличается атомный номер и массовое число при бета-распаде?" },
  { id: 79, category: Category.NUCLEAR, text: "Электроны вылетают из ядер. Означает ли это, что они там есть?" },
  { id: 80, category: Category.NUCLEAR, text: "Задача: Азот-14 захватил альфа-частицу, вылетел протон. Определить неизвестный элемент." },
  { id: 81, category: Category.NUCLEAR, text: "Задача: Энергия расщепления ядра (3p + 3n) равна 36 МэВ. Определить энергию связи." }
];